apiVersion: apps/v1
kind: Deployment
metadata:
  name: java
spec:
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: java
        image: rifielnorth.azurecr.io/mts/java
        ports:
        - containerPort: 8080
